[project]
name = "oipromot"
version = "0.1.0"
description = "Simple CLI for optimizing user input prompts"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
]
